hostname: tarpit

package_update: false
package_upgrade: false

packages:
  - curl
  - wget

runcmd:
  - "cd /tmp && wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_arm64/amazon-ssm-agent.deb"
  - dpkg -i /tmp/amazon-ssm-agent.deb  
  - systemctl enable amazon-ssm-agent
  - systemctl start amazon-ssm-agent
  - apt -y remove openssh-server
  - "curl -s https://raw.githubusercontent.com/babashka/babashka/master/install|bash"

